const UIActionType = {
	CHANGE_FOCUS_GROUP : "CHANGE_FOCUS_GROUP",
	CHANGE_FOCUS_USER : "CHANGE_FOCUS_USER"
};

const GroupActionType = {
	INITIALIZE_GROUP_LIST : "INITIALIZE_GROUP_LIST",
	ADD_GROUP : "ADD_GROUP",
	REMOVE_GROUP : "REMOVE_GROUP",
};

export { UIActionType, GroupActionType };
